### ISSUE TITLE
Do not require 'zend_extension' to be set in php.ini

### ISSUE THREAD

**Issue by denisdanielyan** [lmc-eu/steward#168] opened 2017-11-09 23:27 UTC
Currently debug tests, the 'zend_extension' module needs to be defined in php.ini. This is a bit cumbersome as other programs use the same php environment (i.E. composer). I spent some time until I realised that steward is running the tests by starting a new process for each. This means defining zend_extension in the command line for running steward only loads the module for the steward process, not for the test processes.

So the solution to this problem is to check for the --xdebug argument and then add the zend_extension argument to each spawned php process. Since I did not find the supplied path of the xdebug module, the solution below requires the path to xdebug.so in steward's arguments.

`vendor/bin/steward run staging firefox --xdebug /path/to/xdebug.so`

[processSetCreator.php.patch.txt](https://github.com/lmc-eu/steward/files/1459517/processSetCreator.php.patch.txt)

**Comment by OndraM** [comment] 2017-11-14 09:54
@denisdanielyan Hi, thanks for the report. You are right, Xdebug is actually needed by the child processes, not by the command itself. However moving the check to the child processes will make worse user experience (in case xdebug is not loaded to PHP, every child process would have to fail during execution - however now steward stops on startup). 

But i see the point, there may be some other way how to deal with this, so let me add this to issues for future consideration.

If you need to adjust the behavior right now, you don't need to modify ProcessSetCreator. You can create you on listener (and place it to your `src/Console/EventListener` directory), register it for  CommandEvents::RUN_TESTS_PROCESS event and change the contents of the environment variables passed to the child process there and by this effectively adjust behavior of current [XdebugListener](https://github.com/lmc-eu/steward/blob/master/src/Console/EventListener/XdebugListener.php).

**Comment by denisdanielyan** [comment] 2017-12-03 12:37
Just a thought regarding the worse user experience: I am not certain that I understand your point. From my perspective I usually have the debug argument only set when for example running the process from phpstorm (using the command line option). 
And when things are not right (as for example in your example the argument is pointing to the wrong/no library), I would actually be ok when each process complains about since something is obviously wrong. 

Regarding the implementation: You are most certainly right. The suggested solution was definitely a quick hack that worked without looking too much at the exiting code structure..

**Comment by denisdanielyan** [comment] 2017-12-03 12:38
Just a thought regarding the worse user experience: I am not certain that I understand your point. From my perspective I usually have the debug argument only set when for example running the process from phpstorm (using the command line option). 
And when things are not right (as for example in your example the argument is pointing to the wrong/no library), I would actually be ok when each process complains since something is obviously wrong. 

Regarding the implementation: You are most certainly right. The suggested solution was definitely a quick hack that worked without looking too much at the exiting code structure..

**Comment by OndraM** [comment] 2018-11-12 14:56
Although the issue is still present, after some reconsideration closing for now. It wouldn't be probably easy and reliable (if possible) to automatically determine path do `xdebug.so` (or dll) in an interoperable way, and I don't see other way round. And providing path to xdebug.so as a Steward argument is something we don't want.

However if there is some other solution suggested, we may rethink this.

**Closed as completed by OndraM** 2018-11-12 14:56 UTC
Labels: enhancement, waiting
